#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Checking styling, linting and types before commit. \e[0m"

# Check tsconfig standards
npm run check:types ||
(
    echo "\e[1;31m Oops! The typescript is not happy. Please check your code \e[0m"
    false;
)

# Check ESLint Standards
npm run check:linting ||
(
    echo "\e[1;31m Oops! The linter is not happy. Please run \"npm run lint:fix\"\e[0m"
    false; 
)

# Check Prettier standards
npm run check:formatting ||
(
    echo "Oops! Something is not styled properly \n \e[1;31m Please run \"npm run format\" \e[0m";
    false;
)

# If everything passes... Now we can commit
echo "\e[1;32m Everything checks out. \e[0m"